# Autogenerated wrapper script for Xorriso_jll for armv6l-linux-musleabihf
export xorriso

using Zlib_jll
using Readline_jll
using Bzip2_jll
using Libiconv_jll
using acl_jll
using Attr_jll
JLLWrappers.@generate_wrapper_header("Xorriso")
JLLWrappers.@declare_executable_product(xorriso)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Readline_jll, Bzip2_jll, Libiconv_jll, acl_jll, Attr_jll)
    JLLWrappers.@init_executable_product(
        xorriso,
        "bin/xorriso",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
